config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
  validates :cuteness, numericality: { in: 1..10 }
  validates :softness, numericality: { in: 1..10 }
  validates :age, numericality: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format| 
      format.html
      format.xml { render :xml => @kittens }
      format.json { render :json => @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = 'A new kitten to love!'
      redirect_to @kitten
    else
      flash[:alert] = 'Something went wrong... '
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render :xml => @kitten }
      format.json { render :json => @kitten }
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten, class: "flex flex-col w-9/12 gap-2 self-center" do |form| %>
  <div class="flex">
    <div class="w-72">
      <%= form.label :name, 'Name:' %>
      <%= form.text_field :name %>
    </div>
  </div>

  <div class="flex gap-2 align-middle">
    <div class="w-72">
      <%= form.label :age, 'Age:' %>
      <%= form.text_field :age %>
    </div>
    <% @kitten.errors.full_messages_for(:age).each do |message| %>
      <div class="error-msg"><%= message %></div>
    <% end %>
  </div>

  <div class="flex gap-2 align-middle">
    <div class="w-72">
      <%= form.label :cuteness, 'Cuteness:' %>
      <%= form.text_field :cuteness %>
    </div>
    <% @kitten.errors.full_messages_for(:cuteness).each do |message| %>
      <div class="error-msg"><%= message %></div>
    <% end %>
  </div>

  <div class="flex gap-2 align-middle">
    <div class="w-72">
      <%= form.label :softness, 'Softness:' %>
      <%= form.text_field :softness %>
    </div>
    <% @kitten.errors.full_messages_for(:softness).each do |message| %>
      <div class="error-msg"><%= message %></div>
    <% end %>
  </div>

  <%= form.submit 'Create a Kitten', class: 'nav-button mt-2 w-72' %>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<h1 class="heading-1">Editing <%= @kitten.name %></h1>
<%= render 'form'%>

app/views/kittens/index.html.erb
<h1 class="heading-1">Kittens' List</h1>
<ul class="self-center text-2xl">
  <% unless @kittens.empty? %>
    <% @kittens.each do |kitten| %>
      <li class="group">
        <%= link_to kitten.name, kitten_path(kitten), class: "underline hover:no-underline hover:text-gray-500" %>
        <%= link_to 'Edit', edit_kitten_path(kitten), class: "li-option" %>
        <%= link_to 'Delete', kitten_path(kitten), class: "li-option", data: {
                                                              turbo_method: :delete,
                                                              turbo_confirm: "Are you sure?"
                                                            } %>
      </li>
    <% end %>
  <% else %>
    <li>There are no kittens yet...</li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1 class="heading-1">Make a New Kitten</h1>
<%= render 'form' %>

app/views/kittens/show.html.erb
<h1 class="heading-1"><%= @kitten.name %></h1>
<ul class="self-center text-2xl">
  <li>Age: <%= @kitten.age %></li>
  <li>Cuteness: <%= @kitten.cuteness %></li>
  <li>Softness: <%= @kitten.softness %></li>
</ul>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/_flash.html.erb
<% if flash[:alert] %>
  <div class="block px-6 mt-[-2] text-red-400" role="alert">
    <%= flash[:alert] %>
  </div>
<% elsif flash[:success] %>
  <div class="block px-6 mt-[-2] text-blue-400">
    <%= flash[:success] %>
  </div>
<% else %>
  <div class="block px-6 mt-[-2] text-slate-50 h-6"></div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="mb-4 bg-slate-100 p-8 flex justify-start gap-4">
  <%= link_to 'All Kittens', root_path, class: "nav-button" %>
  <%= link_to 'New Kitten', new_kitten_path, class: "nav-button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container pb-8 flex flex-col">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </main>
  </body>
</html>